### ISSUE TITLE
Sur la Présentation d'un projet, améliorer l'affichage des réponses aux questions 

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#428]
```[tasklist]
### Tasks
- [ ] pour les champs de texte libre, afficher la version courte des questions
- [ ] pour les QCM, afficher la version Conclusion de la réponse et pas la question
- [ ] ramener toutes les réponses dans un même bloc Compléments
- [ ] Enlever les blocs en doublon sur les anciens projets
```

Actuellement sur la Présentation d'un projet, on reprend le libellé intégral des questions issues de la saisine, et en plusieurs blocs : 

![Image](https://github.com/betagouv/recommandations-collaboratives/assets/16819425/ace10efb-0df2-498a-a8ca-594368a29771)

- A la place, il faut afficher la version courte de la question, pour les questions ouvertes : 

![Image](https://github.com/betagouv/recommandations-collaboratives/assets/16819425/c3df4aef-2081-4787-9b95-3711502f9031)

- Quand la question est un QCM, n'afficher que la version longue de la réponse (pas la question)

- Et ramener toutes les réponses dans un même bloc Compléments, comme ci-dessous : 

![Image](https://github.com/betagouv/recommandations-collaboratives/assets/16819425/a86654d4-303c-4c81-b72b-05491192646f)

- Enlever les blocs en doublon sur les anciens projets ([voir sur ce projet](https://urbanvitaliz.fr/project/1290/presentation), cartofriche est affiché 2x), au profit de tout mettre dans un même bloc Compléments

**Comment by sabinesafi** [comment]
Dans le cas d'un QCM, voir si on affiche quetsion et réponse ou que réponse, longue ou courte, etc.

**Comment by sabinesafi** [comment]
@Jeremy-Bojko s'il est encore temps, peux-tu modifier le wording "Contexte" en "Résumé du projet" stp ?
