### ISSUE TITLE
ETQ conseiller, je peux accéder à la vue kanban du tableau de bord

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#429]
Depuis l'anciennement 'tableau de bord conseiller', qui devient la vue liste : etq conseiller je peux accéder à la vue tableau (le kanban).
Pour ça on rajoute la barre d'actions du kanban et on enlève la barre d'actions qui vit actuellement entre la map et les cartes projet.
[Maquette figma ici](https://www.figma.com/design/VM4w7YyghKkcIZsZIGlp0Q/Kanban-Staff?node-id=223-130&t=44mEmWtToWICfyyY-0)

On ne modifie pas le reste de la page si possible pour minimiser le travail dessus.

Par défaut, au clic sur Accueil, les conseillers sont envoyés sur la vue liste et les staffs sur la vue tableau.

```[tasklist]
### Tasks
- [ ] Supprimer la barre d'actions qui vit actuellement entre la map et les cartes projet.
- [x] Rajouter la nouvelle barre d'actions du kanban staff
- [x] Permettre aux conseillers d'afficher le kanban
- [x] Envoyer les conseillers sur la vue Liste et les staffs sur la vue tableau
```

**Comment by SebastienReuiller** [comment]
"Envoyer les conseillers sur la vue Liste et les staffs sur la vue tableau"
C'est déjà le cas quand on visite "/projects".
