### ISSUE TITLE
Créer un espace de paramétrage du portail dans le CRM et y mettre toutes les infos du portail

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#431]
```[tasklist]
### Tasks
```

**Comment by Jeremy-Bojko** [comment]
Note pour l'intégration : 
- [ ] Utiliser crispy form
- [ ] Ajouter du padding sur le form
- [ ] Ajouter la gestion du champ type number
- [ ] Ajouter la gestion du champ type file
