### ISSUE TITLE
[Multi PF] Gérer les notifs sur les projets multipubliés

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#442]
S'assurer qu'il n'y ait pas de mail en doublon (ex : notifs nvlles recos à la collectivité, quand commentaire sur une reco on notifie qui etc.)
Comment on gère si le conseiller est sur 2 PF
Côté collectivités, on envoie toutes les notifs sur la PF d'origine
```[tasklist]
### Tasks
- [ ] Lors d'un dispatch de notif vers la collectivité, envoyer celle ci vers le site source du projet
- [ ] Si on doit dispatch une notif à tous les conseillers, on la duplique pour chacune des PF concernées
- [ ] si on doit cibler un conseiller en particulier, on privilégie le site de dépot du projet en cas de plusieurs rattachements à des PFs. Sinon, prendre la première, au hasard
```

**Comment by glibersat** [comment]
Dépend de #447
